version: "3.4"

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: .env
    ports:
      - 5555:5555
    links:
      - mongo
    command: npm run dev
  mongo:
    container_name: mongo
    image: mongo:5.0.2
    env_file: .env
    ports:
      - 27017:27017
